### PR TITLE
Japanese Translation

### PR DESCRIPTION
**Pull request by mumumu-ko**
Firstly, I translated menus and so on.

### CODE REVIEW

**Review by denysdovhan — CHANGES_REQUESTED** [review]
Please, translate other exercises to Japanese too.

**Comment by mumumu-ko** [comment]
I also translated other exercises.

**Comment by mumumu-ko** [comment]
@denysdovhan  
please review again.

**Comment by denysdovhan** [comment]
@mumumu-ko thanks! However, I can't review properly, since I don't understand Japanese :(

**Review by denysdovhan — APPROVED** [review]
I hope you've done this well.

**Pull request merged**
