### PR TITLE
Add exception rule to Tables exercise.

### LINKED ISSUE #22: Tables challenge
In the introduction, it says: 

```
There are a few important things here:  

   » There must be at least 3 dashes separating each header cell.       

```

It says at least 3 dashes.

In the solution:

```
Solution ===================  

     # Tables  

     | Year | World population |  
     | :--: | ---------------- |  
     | 1960 | 3 Billion        |  

```

It uses two dashes in the 'Year' column.  Shall we add an exception to the rule ('align columns counts as dashes'), or just add one more dash to the solution to make it consistent.

### PR DESCRIPTION
**Pull request by itzsaga**
I noticed that this was never closed so here it is. Exact same fix that @academyofzhuang made so credit to him. I think he just never did a PR.

Fixes: https://github.com/workshopper/how-to-markdown/issues/22

### CODE REVIEW

**Comment by itzsaga** [comment]
I just realized why there are two commits in this PR. My bad, trying to do better with branches and see what I did.

**Comment by denysdovhan** [comment]
LGTM

BTW, @itzsaga thanks for taking the lead at this project. I don't have enough time currently (I'm changing the job), my bad.

**Comment by itzsaga** [comment]
You're more than welcome @denysdovhan.

**Review by denysdovhan — COMMENTED** [review]
LGTM

**Pull request merged**
